### ISSUE TITLE
live preview of the editor content

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#15]

**Comment by seebi** [comment]
http://jrmoran.com/playground/markdown-live-editor/

**Comment by k00ni** [comment]
8a19456ed9dd2e3f33c9ac335fcfaefd7839d3d7 fixes this issue

**Comment by seebi** [comment]
there is a bug with the refresh. the content is show correctly after the first edit first ...

**Comment by k00ni** [comment]
Your 955e814712c5fe384860af36b0e9dba82338fb7e destroyed the whole editAction, for instance the preview is now located under the editor textfield, your submit button does not work and there parts in the user interface which are looks ugly now (some scrollbar at the bottom). 

Is it possible for the future that you simply open an issue and let us doing the work? :) Now we have to located the stuff which causes the problems in the user interface and fix it. For instance where locating the preview area now? It seems your buttons need same space which our editor will don't have anymore.

**Comment by seebi** [comment]
regarding the button row: yes, thats true. I wanted to ask you to fix that :-)

**Comment by seebi** [comment]
regarding the ui: the whole edit.phtml is a mess without any quality standard. Since you made clear that you do not want to work anymore on this extension, I started to going forward and cleanup.

most of your GUI elements does not fit into OW standard look and feel which is not acceptable (even when it looks better what it imho does not do)

**Comment by k00ni** [comment]
_Is [this file](https://github.com/AKSW/OntoWiki/blob/develop/application/views/templates/partials/list_std_main.phtml) of OntoWiki in any quality standard? ;)_

_Anyway, let us put the beef away and focus on the topic "get the component ready to use". If you want corrections of the user interface please say it. The component is still under development and if nobody say anything, we can not correct it._

What do you mean with

> the content is show correctly after the first edit first ...

Is the preview correct AFTER the first edit? And BEFORE its not? Where do you want to locate the Preview area?

**Comment by seebi** [comment]
you hunted the most evil file in the repo :)
(btw. also this file started with a few lines of code and nobody wanted to make a QS)

**Comment by seebi** [comment]
here is an example

this is what I see just after clicking on the Article Tab:
![before](https://f.cloud.github.com/assets/510452/11019/6aae4a9e-453e-11e2-8fb6-8e7de40dbfff.png)

this is what I see just after typing the "ttt: (now it is correct)
![after](https://f.cloud.github.com/assets/510452/11018/6a7b22cc-453e-11e2-8785-900026116c67.png)

**Comment by seebi** [comment]
regarding the position of the preview area: currently  I'm happy with its location right beside the input field

do you think its better to have it below the area?

**Comment by seebi** [comment]
the new image upload is awesome! :)

**Comment by k00ni** [comment]
> the new image upload is awesome! :)

What image upload?

Is the update-bug still there? (Should be fixed with dbe071aa4486c8d4995c3c132822ea164922d794)

The position of the preview area is under the editor-textarea, because there isn't enough space at the right side. It will be extendable, is that ok?

**Comment by seebi** [comment]
image upload -> the new github image upload

the update bug is fixed, the position is also ok for me, thanks
