### ISSUE TITLE
gui: please use standard toolbar for article tab

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#23]
this includes the standard messaging system

**Comment by seebi** [comment]
I added the toolbar with two buttons. cancel works fine but submit need to be fixed.

@k00ni : can you please delete the botton screen and attach the functionality to the new submit button?

**Comment by k00ni** [comment]
Is done. :)

**Comment by seebi** [comment]
I've just tested the new submit button with firefox as well as chrome (both macos) and it does not work. There is an ajax call but the resource is still the same.

**Comment by seebi** [comment]
ok, filed as new bug issue #30
