### ISSUE TITLE
please use the resourcecreationuri extension for adding new resources

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#25]

**Comment by seebi** [comment]
This feature is imho crucial since it integrates the "createing new pages" use case well in OntoWiki. Without this feature, we can not use it to create new resources since we will have these hashed-URIs then.

The implementation side is not so complicated. You just need to send a simplified UPDATE POST of the resource update endpoint just as this is done by RDFauthor here:
https://github.com/AKSW/RDFauthor/blob/develop/src/rdfauthor.js#L1030

This even simplifies your component since you do not need your own callback service ...

**Comment by k00ni** [comment]
e677deeb67494fb7ab3dfb20e636a2141bde7276 and following commits fix this issue. But there UPDATE POST but we used INSERT + DELETE to update an existing resource.
