### ISSUE TITLE
code sniffing issues?

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#29]
can you please enable code sniffing in your dev environments and fix all cs issues in the module?

**Comment by larseidam** [comment]
i have merged your latest changes. Please don't assign me again to an issue if you do it by yourself in the end. So we dont have to fix issues twice. :)

**Comment by seebi** [comment]
I still can not install the cs makefile. Can we move the coffeescript make file to public/typescript?

btw: why is the typescript in the public folder?

**Comment by seebi** [comment]
mhmm sorry. I  started with the controller and dont wanted to finish that mess so I added an issue. I hoped you pull before starting the issue ...

**Comment by k00ni** [comment]
By the way, its not coffeescript its TypeScript :)

It is moved to article's main folder, with the Makefile! (see 4e64141f89f493f79f1368c18ac4741eb044ad0a)

**Comment by seebi** [comment]
ok, thanks
