### ISSUE TITLE
visual feedback of save action

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#31]
usually we add something like that at the beginning of the content after success:

<pre>&lt;p class="messagebox success"&gt;Article saved&lt;/p&gt;</pre>

or after failure:

<pre>&lt;p class="messagebox error"&gt;Saving not possible&lt;/p&gt;</pre>

In this case, you could fade this away just as you've dont that with the old save feedback at the bottom

**Comment by k00ni** [comment]
c1831880eb4e6f91902edec09526d0b5dab986d2 and bd68c569123d18ba5c01172de42b77ecfc710521 fixes the issue.

**Comment by seebi** [comment]
works fine

**Comment by k00ni** [comment]
great, than close :)
